name: "Build and Deploy"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: aspdotnetswagger  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '3.1.101'                    # set this to the .NET Core version to use

defaults:
  run:
    shell: bash
    working-directory: DotNet-Azure-Swagger/myProject

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration Release --no-restore

    - name: Test app
      run: dotnet test --no-build

    - name: Publish app for deploy
      run: dotnet publish --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: /home/runner/work/.NET-Core-Development-with-Azure-and-Swagger/.NET-Core-Development-with-Azure-and-Swagger/DotNet-Azure-Swagger/myProject/published/

    - name: PowerShell script
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script:  /home/runner/work/.NET-Core-Development-with-Azure-and-Swagger/.NET-Core-Development-with-Azure-and-Swagger/script.ps1

    
#     - name: Publish Artifacts
#       uses: actions/upload-artifact@v1.0.0
#       with:
#         name: webapp
#         path:  /home/runner/work/.NET-Core-Development-with-Azure-and-Swagger/.NET-Core-Development-with-Azure-and-Swagger/DotNet-Azure-Swagger/myProject/published/
      
#     - name: change chmod
#       run: chmod +x /home/runner/work/.NET-Core-Development-with-Azure-and-Swagger/.NET-Core-Development-with-Azure-and-Swagger/script.sh
      
#     - name: Script
#       run:  /home/runner/work/.NET-Core-Development-with-Azure-and-Swagger/.NET-Core-Development-with-Azure-and-Swagger/script.sh

      
      
#     - name: Update Azure API Management Services
#       uses: kipriz/update-azure-api-management@v1
#       with:
#         subscriptionId: "faab79a5-d424-4699-b3ff-b0cf94ea9f90" # Subscription ID from Azure's Subscriptions
#         resourceGroup: "aspdotnetswagger" # Resource Group name
#         serviceName: "aspdotnetswagger" # Name of API in API Management
#         apiName: "dotnetswagger" # API Name. Pick it up from tracing request when you open a specific API in "API Management Services" -> APIS 
#         authorization: "SharedAccessSignature integration&202112301804&dmW3gLaar4hUe74hJC1skWm2ze7cmmUk/q6SXF6nPaJ+2/62ZFswfsRyAS3uxZmCTYemSpXp6cu8n3LsyFkVpw==" # authorization from "API Management Services" -> "Management API"  
#         apiPath: "itisfromapim"
#         openApiLink: "https://aspdotnetswagger.azurewebsites.net/azure_swagger_dotnet/swagger/v1/swagger.json"
       
       
   
#     - name: PowerShell script
#       # You may pin to the exact commit or the version.
#       # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
#       uses: Amadevus/pwsh-script@v2.0.1
#       with:
#         # PowerShell script to execute in Actions-hydrated context
#         script: az login -u "naman786sinha@gmail.com" -p "thinkMS123" ;  az apim api import -g aspdotnetswagger --service-name aspdotnetswagger --path itisfromapim --specification-url "https://aspdotnetswagger.azurewebsites.net/azure_swagger_dotnet/swagger/v1/swagger.json" --specification-format OpenApiJson --api-id "DotnetSwagger" --display-name "DotnetSwagger"


